// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/AutoDrivePath.h"

#include <frc/Filesystem.h>
#include <frc/trajectory/TrajectoryUtil.h>
#include <spdlog/spdlog.h>
#include <fstream>
#include <spdlog/fmt/ostr.h>
#include <wpi/SmallString.h>

AutoDrivePath::AutoDrivePath(const char *pathName, bool resetOdometry, Drivetrain *m_drivetrain) :
    m_pathName(pathName),
    m_resetOdometry(resetOdometry),
    m_drivetrain(m_drivetrain)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("AutoDrivePath");
    AddRequirements(m_drivetrain);

    // Get our trajectory
    // TODO: Move this to be able to load a trajectory while disabled when
    //          the user changes the chooser selection
    std::string outputDirectory = frc::filesystem::GetDeployDirectory();
    outputDirectory.append(std::string("/output/") + m_pathName + ".wpilib.json");
    spdlog::info("DTR Output Directory is: {}", outputDirectory);
    std::ifstream pathFile(outputDirectory.c_str());
    if (pathFile.good())
        spdlog::info("DTR pathFile is good");
    else
        spdlog::error("DTR pathFile not good");

    m_trajectory = frc::TrajectoryUtil::FromPathweaverJson(outputDirectory);
}

// Called just before this Command runs the first time
void AutoDrivePath::Initialize()
{
    spdlog::info("AutoDrivePath - Init: pathName: {}", m_pathName);
    m_drivetrain->RamseteFollowerInit(m_trajectory, m_resetOdometry);
}

// Called repeatedly when this Command is scheduled to run
void AutoDrivePath::Execute()
{
    m_drivetrain->RamseteFollowerExecute();
}

// Make this return true when this Command no longer needs to run execute()
bool AutoDrivePath::IsFinished()
{
    return false;
}

// Called once after isFinished returns true
void AutoDrivePath::End(bool interrupted)
{
    m_drivetrain->RamseteFollowerEnd();
}

bool AutoDrivePath::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
