// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include <spdlog/spdlog.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/AutoStop.h"

AutoStop::AutoStop(Drivetrain *m_drivetrain) : m_drivetrain(m_drivetrain)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("AutoStop");
    AddRequirements(m_drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
}

// Called just before this Command runs the first time
void AutoStop::Initialize()
{
    spdlog::info("AutoStop - Init");
}

// Called repeatedly when this Command is scheduled to run
void AutoStop::Execute()
{
    m_drivetrain->MoveStop();
}

// Make this return true when this Command no longer needs to run execute()
bool AutoStop::IsFinished()
{
    return false;
}

// Called once after isFinished returns true
void AutoStop::End(bool interrupted)
{
    spdlog::info("AutoStop - End");
}

bool AutoStop::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
