// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/Climber4EXTENDTOL3.h"
#include "commands/Climber5ROTATEINTOL3.h"
#include "commands/Climber6CLIMBTOL3.h"
#include "frc2135/RobotConfig.h"

#include <spdlog/spdlog.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/ClimberClimbL3.h"

ClimberClimbL3::ClimberClimbL3(Climber *climber)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ClimberClimbL3");

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    // Add your commands here, e.g.
    // AddCommands(FooCommand(), BarCommand());

    // Climber raises to 31.5 inches
    // Gate hook activated (extended) still
    // Climber stays at 31.5 inches (no movement)
    // Gate hook move to default position (closed)
    // Climber lowers to 0.25 inches
    // Gate hook is at default position

    AddCommands(ClimberExtendToL3(climber), ClimberRotateIntoL3(climber), ClimberClimbToL3(climber));
}

bool ClimberClimbL3::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}