// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "RobotContainer.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <spdlog/spdlog.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/ClimberMoveHeight.h"

ClimberMoveHeight::ClimberMoveHeight(Climber *m_climber) : m_climber(m_climber)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ClimberMoveHeight");
    AddRequirements(m_climber);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
}

// Called just before this Command runs the first time
void ClimberMoveHeight::Initialize()
{
    spdlog::info("ClimberMoveHeight - Init");

    spdlog::info("Climber Target Height = {}", m_targetHeight);
    m_climber->SetClimberSpeed();
    m_climber->MoveClimberDistanceInit(m_targetHeight);
}

// Called repeatedly when this Command is scheduled to run
void ClimberMoveHeight::Execute()
{
    frc::SmartDashboard::PutNumber("CL_Target Height", m_targetHeight);
    m_targetHeight = frc::SmartDashboard::GetNumber("CL_Target Height", 0.0);
}

// Make this return true when this Command no longer needs to run execute()
bool ClimberMoveHeight::IsFinished()
{
    return false;
}

// Called once after isFinished returns true
void ClimberMoveHeight::End(bool interrupted)
{
    spdlog::info("ClimberMoveHeight - End");
}

bool ClimberMoveHeight::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
