// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/RobotInitialize.h"

#include <spdlog/spdlog.h>

RobotInitialize::RobotInitialize()
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("RobotInitialize");
}

// Called just before this Command runs the first time
void RobotInitialize::Initialize()
{
    spdlog::info("RobotInitialize - Init");

    RobotContainer *robotContainer = RobotContainer::GetInstance();
    robotContainer->m_drivetrain.Initialize();
    robotContainer->m_intake.Initialize();
    robotContainer->m_floorConv.Initialize();
    robotContainer->m_vertConv.Initialize();
    robotContainer->m_shooter.Initialize();
    robotContainer->m_climber.Initialize();
    robotContainer->m_pneumatics.Initialize();
    robotContainer->m_power.Initialize();
    robotContainer->m_led.Initialize();
}

// Called repeatedly when this Command is scheduled to run
void RobotInitialize::Execute() {}

// Make this return true when this Command no longer needs to run execute()
bool RobotInitialize::IsFinished()
{
    return true;
}

// Called once after isFinished returns true
void RobotInitialize::End(bool interrupted)
{
    spdlog::info("RobotInitialize - End");
}

bool RobotInitialize::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return true;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
