// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "RobotContainer.h"

#include <spdlog/spdlog.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

#include "commands/ShooterReverse.h"

ShooterReverse::ShooterReverse(Shooter *m_shooter) : m_shooter(m_shooter)
{
    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("ShooterReverse");
    AddRequirements(m_shooter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
}

// Called just before this Command runs the first time
void ShooterReverse::Initialize()
{
    spdlog::info("ShooterReverse - Init");
    m_shooter->ShooterReverseInit();
}

// Called repeatedly when this Command is scheduled to run
void ShooterReverse::Execute()
{
    m_shooter->ShooterReverseExecute();
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterReverse::IsFinished()
{
    return false;
}

// Called once after isFinished returns true
void ShooterReverse::End(bool interrupted)
{
    spdlog::info("ShooterReverse - End");
    m_shooter->ShooterReverseEnd();
}

bool ShooterReverse::RunsWhenDisabled() const
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
}
