// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "frc2135/RobotConfig.h"
#include "frc2135/TalonUtils.h"

#include <frc/RobotController.h>
#include <spdlog/fmt/ostr.h>
#include <spdlog/spdlog.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/Intake.h"

#include <frc/smartdashboard/SmartDashboard.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#undef CAN

Intake::Intake()
{
    SetName("Intake");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("Intake");

    AddChild("Position", &m_position);

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

// Validate Talon FX controllers, initialize and display firmware versions
#ifdef CAN
    m_talonValidIN6 = frc2135::TalonUtils::TalonCheck(m_motorIN6, "IN", "IN6");
#endif
    frc::SmartDashboard::PutBoolean("HL_IN6Valid", m_talonValidIN6);

    // Check if solenoids are functional or blacklisted
    if (m_position.IsDisabled())
        spdlog::error("IN Intake Deploy Solenoid is BLACKLISTED");
    else
        spdlog::info("IN Intake Deploy Solenoid is FUNCTIONAL");

    // Initialize Variables
    frc2135::RobotConfig *config = frc2135::RobotConfig::GetInstance();
    config->GetValueAsDouble("IN_AcquireSpeed", m_acquireSpeed, 0.6);
    config->GetValueAsDouble("IN_ExpelSpeed", m_expelSpeed, -0.6);

    m_motorIN6.SetInverted(true);
    m_motorIN6.SetSafetyEnabled(false);

#ifndef CAN
    m_motorIN6.Set(0.0);
#endif

#ifdef CAN
    if (m_talonValidIN6)
    {
        // Set motor directions
        // Turn on Coast mode (not brake)
        // Set motor peak outputs
        m_motorIN6.SetNeutralMode(NeutralMode::Coast);

        //m_motorIN6.ConfigVoltageCompSaturation(12.0, 0);
        //m_motorIN6.EnableVoltageCompensation(true);

        m_motorIN6.ConfigSupplyCurrentLimit(m_supplyCurrentLimits);
        m_motorIN6.ConfigStatorCurrentLimit(m_statorCurrentLimits);

        m_motorIN6.SetStatusFramePeriod(Status_1_General_, 255, kCANTimeout);
        m_motorIN6.SetStatusFramePeriod(Status_2_Feedback0_, 255, kCANTimeout);
    }
#endif

    Initialize();
}

void Intake::Periodic()
{
#if 0
    static int periodicInterval = 0;

    // Put code here to be run every 20 ms loop

    // Only update indicators every 100 ms to cut down on network traffic
    if (periodicInterval++ % 5 == 0)
    {
        double outputIN6 = 0.0;

        if (m_talonValidIN6)
            outputIN6 = m_motorIN6.GetMotorOutputPercent();

        frc::SmartDashboard::PutNumber("IN_Output_IN6", outputIN6);

        if (m_intakeDebug > 0)
        {
            double currentIN6 = 0.0;

            if (m_talonValidIN6)
                currentIN6 = m_motorIN6.GetOutputCurrent();

            frc::SmartDashboard::PutNumber("IN_Current_IN6", currentIN6);
        }
    }
#endif
#ifdef CAN
    if (m_motorIN6.HasResetOccurred())
    {
        m_countIN6 += 1;
        frc::SmartDashboard::PutNumber("HL_Resets_IN6", m_countIN6);
    }
#endif
}

void Intake::SimulationPeriodic()
{
    // This method will be called once per scheduler run when in simulation
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Intake::Initialize(void)
{
    spdlog::info("IN Init");
    SetIntakeSpeed(INTAKE_STOP);
    SetDeployerSolenoid(false);
}

// Dump all Talon faults
void Intake::FaultDump(void)
{
#ifdef CAN
    frc2135::TalonUtils::TalonFaultDump("IN 6", m_motorIN6);
#endif
}

// Set mode of intake
void Intake::SetIntakeSpeed(int mode)
{
    const char *strName;
    double output = 0.0; // Default: off

    switch (mode)
    {
        default:
        case INTAKE_STOP:
            strName = "STOP";
            output = 0.0;
            break;
        case INTAKE_ACQUIRE:
            strName = "ACQUIRE";
            output = m_acquireSpeed;
            break;
        case INTAKE_EXPEL:
            strName = "EXPEL";
            output = m_expelSpeed;
            break;
    }

    // Set speed of intake and the percent output
    spdlog::info("IN Set Speed - {}", strName);

#ifdef CAN
    if (m_talonValidIN6)
        m_motorIN6.Set(ControlMode::PercentOutput, output);
#else
    m_motorIN6.Set(output);
#endif
}

void Intake::SetDeployerSolenoid(bool extended)
{
    spdlog::info("IN Intake {}", (extended) ? "DEPLOY" : "STOW");
    frc::SmartDashboard::PutBoolean("IN_Deployed", extended);

    m_position.Set(extended);
}
