
clang-format -i ./src/main/java/frc/robot/RobotContainer.java
clang-format -i ./src/main/java/frc/robot/Robot.java
clang-format -i ./src/main/java/frc/robot/Main.java
clang-format -i ./src/main/java/frc/robot/subsystems/FloorConveyor.java
clang-format -i ./src/main/java/frc/robot/subsystems/Drivetrain.java
clang-format -i ./src/main/java/frc/robot/subsystems/Intake.java
clang-format -i ./src/main/java/frc/robot/subsystems/Pneumatics.java
clang-format -i ./src/main/java/frc/robot/subsystems/LED.java
clang-format -i ./src/main/java/frc/robot/subsystems/Climber.java
clang-format -i ./src/main/java/frc/robot/subsystems/Vision.java
clang-format -i ./src/main/java/frc/robot/subsystems/Power.java
clang-format -i ./src/main/java/frc/robot/subsystems/Shooter.java
clang-format -i ./src/main/java/frc/robot/subsystems/TowerConveyor.java
clang-format -i ./src/main/java/frc/robot/commands/AutoDriveShoot.java
clang-format -i ./src/main/java/frc/robot/commands/AutoWait.java
clang-format -i ./src/main/java/frc/robot/commands/RobotInitialize.java
clang-format -i ./src/main/java/frc/robot/commands/AutoShootDriveShoot.java
clang-format -i ./src/main/java/frc/robot/commands/ExhaustingStop.java
clang-format -i ./src/main/java/frc/robot/commands/DriveQuickturn.java
clang-format -i ./src/main/java/frc/robot/commands/Climber5RotateIntoL3.java
clang-format -i ./src/main/java/frc/robot/commands/DriveLimelightShoot.java
clang-format -i ./src/main/java/frc/robot/commands/IntakingStop.java
clang-format -i ./src/main/java/frc/robot/commands/ScoringPrime.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberRun.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberMoveToHeight.java
clang-format -i ./src/main/java/frc/robot/commands/Auto1Ball1OppRight.java
clang-format -i ./src/main/java/frc/robot/commands/LEDSet.java
clang-format -i ./src/main/java/frc/robot/commands/ShooterReverse.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberSetGatehook.java
clang-format -i ./src/main/java/frc/robot/commands/Climber7ClimbToL4.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberCalibrate.java
clang-format -i ./src/main/java/frc/robot/commands/AutoDrive.java
clang-format -i ./src/main/java/frc/robot/commands/AutoShootLowHub.java
clang-format -i ./src/main/java/frc/robot/commands/AutoShoot.java
clang-format -i ./src/main/java/frc/robot/commands/IntakeRun.java
clang-format -i ./src/main/java/frc/robot/commands/Climber1Deploy.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberL2ToL3.java
clang-format -i ./src/main/java/frc/robot/commands/ShooterAim.java
clang-format -i ./src/main/java/frc/robot/commands/AutoDrivePath.java
clang-format -i ./src/main/java/frc/robot/commands/Climber0Stow.java
clang-format -i ./src/main/java/frc/robot/commands/Climber8SettleToL4.java
clang-format -i ./src/main/java/frc/robot/commands/ExhaustingAction.java
clang-format -i ./src/main/java/frc/robot/commands/AutoDriveLimelightShoot.java
clang-format -i ./src/main/java/frc/robot/commands/Auto3BallRight.java
clang-format -i ./src/main/java/frc/robot/commands/Auto1BallLimelight.java
clang-format -i ./src/main/java/frc/robot/commands/ScoringActionHighHub.java
clang-format -i ./src/main/java/frc/robot/commands/DriveSlowMode.java
clang-format -i ./src/main/java/frc/robot/commands/ScoringActionLowHub.java
clang-format -i ./src/main/java/frc/robot/commands/DriveLimelight.java
clang-format -i ./src/main/java/frc/robot/commands/IntakeDeploy.java
clang-format -i ./src/main/java/frc/robot/commands/ShooterRun.java
clang-format -i ./src/main/java/frc/robot/commands/IntakingAction.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberFullClimb.java
clang-format -i ./src/main/java/frc/robot/commands/AutonomousCommand.java
clang-format -i ./src/main/java/frc/robot/commands/Dummy.java
clang-format -i ./src/main/java/frc/robot/commands/Climber2ClimbToL2.java
clang-format -i ./src/main/java/frc/robot/commands/DriveTeleop.java
clang-format -i ./src/main/java/frc/robot/commands/AutoPathSequence.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberL3ToL4.java
clang-format -i ./src/main/java/frc/robot/commands/Climber6ClimbToL3.java
clang-format -i ./src/main/java/frc/robot/commands/AutoStop.java
clang-format -i ./src/main/java/frc/robot/commands/DriveLimelightStop.java
clang-format -i ./src/main/java/frc/robot/commands/ShooterAimToggle.java
clang-format -i ./src/main/java/frc/robot/commands/DriveResetSensors.java
clang-format -i ./src/main/java/frc/robot/commands/FloorConveyorRun.java
clang-format -i ./src/main/java/frc/robot/commands/Auto1Ball2OppLeft.java
clang-format -i ./src/main/java/frc/robot/commands/SimulateLimelight.java
clang-format -i ./src/main/java/frc/robot/commands/DriveMotorTest.java
clang-format -i ./src/main/java/frc/robot/commands/Climber3RotateToL3.java
clang-format -i ./src/main/java/frc/robot/commands/ClimberTimerOverride.java
clang-format -i ./src/main/java/frc/robot/commands/Auto3BallLeft.java
clang-format -i ./src/main/java/frc/robot/commands/ScoringStop.java
clang-format -i ./src/main/java/frc/robot/commands/TowerConveyorRun.java
clang-format -i ./src/main/java/frc/robot/Constants.java
